on:
  push:
    branches: [main]

jobs:
  evaluate_variables:
    runs-on: ubuntu-latest
    name: Job to evaluate variables
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: evaluate variables step
        uses: asvataa/set-vars-by-prefix@main
        with:
          variables: ${{ toJSON(vars) }}
          varsPrefix: TEST

      - name: Get the output variables
        run: |
          echo "check environment ${{ env.ENVIRONMENT }}"
          echo "check username ${{ env.USERNAME }}"
          env
